// <auto-generated/>
namespace Generate_Flows_1.NTP_RCP
{
	using System.ComponentModel;
	using Generate_Flows_1.QActionHelpers;

	public static class Parameter
	{
		/// <summary>PID: 11 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int fixed01_11 = 11;

		/// <summary>PID: 11 | Type: read</summary>
		public const int fixed01 = 11;

		/// <summary>PID: 12 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int fixed1400_12 = 12;

		/// <summary>PID: 12 | Type: read</summary>
		public const int fixed1400 = 12;

		/// <summary>PID: 13 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int fixed0000_13 = 13;

		/// <summary>PID: 13 | Type: read</summary>
		public const int fixed0000 = 13;

		/// <summary>PID: 51 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int responsedata_51 = 51;

		/// <summary>PID: 51 | Type: read</summary>
		public const int responsedata = 51;

		/// <summary>PID: 160 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int sourcetoconnectordisconnect_160 = 160;

		/// <summary>PID: 160 | Type: read</summary>
		public const int sourcetoconnectordisconnect = 160;

		/// <summary>PID: 161 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int destinationtoconnectordisconnect_161 = 161;

		/// <summary>PID: 161 | Type: read</summary>
		public const int destinationtoconnectordisconnect = 161;

		/// <summary>PID: 162 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int protectsource_162 = 162;

		/// <summary>PID: 162 | Type: read</summary>
		public const int protectsource = 162;

		/// <summary>PID: 163 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int protectdestination_163 = 163;

		/// <summary>PID: 163 | Type: read</summary>
		public const int protectdestination = 163;

		/// <summary>PID: 164 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int protectvalue_164 = 164;

		/// <summary>PID: 164 | Type: read</summary>
		public const int protectvalue = 164;

		/// <summary>PID: 165 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rcpdelaymutegaindirection_165 = 165;

		/// <summary>PID: 165 | Type: read</summary>
		public const int rcpdelaymutegaindirection = 165;

		/// <summary>PID: 166 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rcpdelaymutegainlinetype_166 = 166;

		/// <summary>PID: 166 | Type: read</summary>
		public const int rcpdelaymutegainlinetype = 166;

		/// <summary>PID: 167 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rcpdelaymutegainline_167 = 167;

		/// <summary>PID: 167 | Type: read</summary>
		public const int rcpdelaymutegainline = 167;

		/// <summary>PID: 168 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rcpdelaytoset_168 = 168;

		/// <summary>PID: 168 | Type: read</summary>
		public const int rcpdelaytoset = 168;

		/// <summary>PID: 169 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rcpgainhightoset_169 = 169;

		/// <summary>PID: 169 | Type: read</summary>
		public const int rcpgainhightoset = 169;

		/// <summary>PID: 170 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rcpgainlowtoset_170 = 170;

		/// <summary>PID: 170 | Type: read</summary>
		public const int rcpgainlowtoset = 170;

		/// <summary>PID: 171 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rcpmutetoset_171 = 171;

		/// <summary>PID: 171 | Type: read</summary>
		public const int rcpmutetoset = 171;

		/// <summary>PID: 172 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rcpphasetoset_172 = 172;

		/// <summary>PID: 172 | Type: read</summary>
		public const int rcpphasetoset = 172;

		/// <summary>PID: 499 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int parkinputdependencyvalues_499 = 499;

		/// <summary>PID: 499 | Type: read</summary>
		public const int parkinputdependencyvalues = 499;

		/// <summary>PID: 500 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int parkinput_500 = 500;

		/// <summary>PID: 500 | Type: read</summary>
		public const int parkinput = 500;

		/// <summary>PID: 1000 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rcpversion_1000 = 1000;

		/// <summary>PID: 1000 | Type: read</summary>
		public const int rcpversion = 1000;

		/// <summary>PID: 1001 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rcpnumberofusers_1001 = 1001;

		/// <summary>PID: 1001 | Type: read</summary>
		public const int rcpnumberofusers = 1001;

		/// <summary>PID: 1002 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rcpnumberofmatrices_1002 = 1002;

		/// <summary>PID: 1002 | Type: read</summary>
		public const int rcpnumberofmatrices = 1002;

		/// <summary>PID: 1003 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rcpnumberofmacros_1003 = 1003;

		/// <summary>PID: 1003 | Type: read</summary>
		public const int rcpnumberofmacros = 1003;

		/// <summary>PID: 1004 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rcpnumberofvirtualgpis_1004 = 1004;

		/// <summary>PID: 1004 | Type: read</summary>
		public const int rcpnumberofvirtualgpis = 1004;

		/// <summary>PID: 1005 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rcpnumberofsources_1005 = 1005;

		/// <summary>PID: 1005 | Type: read</summary>
		public const int rcpnumberofsources = 1005;

		/// <summary>PID: 1006 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rcpnumberofdestinations_1006 = 1006;

		/// <summary>PID: 1006 | Type: read</summary>
		public const int rcpnumberofdestinations = 1006;

		/// <summary>PID: 1007 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rcpnumberoflevels_1007 = 1007;

		/// <summary>PID: 1007 | Type: read</summary>
		public const int rcpnumberoflevels = 1007;

		/// <summary>PID: 9000000 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int clp_interapp_receive_9000000 = 9000000;

		/// <summary>PID: 9000000 | Type: read</summary>
		public const int clp_interapp_receive = 9000000;

		/// <summary>PID: 9000001 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int clp_interapp_return_9000001 = 9000001;

		/// <summary>PID: 9000001 | Type: read</summary>
		public const int clp_interapp_return = 9000001;

		public class Write
		{
			/// <summary>PID: 550 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int parkinput_550 = 550;

			/// <summary>PID: 550 | Type: write</summary>
			public const int parkinput = 550;

			/// <summary>PID: 1010 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int refreshconfiguration_1010 = 1010;

			/// <summary>PID: 1010 | Type: write</summary>
			public const int refreshconfiguration = 1010;

			/// <summary>PID: 5053 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int sourcesdelay_5053 = 5053;

			/// <summary>PID: 5053 | Type: write</summary>
			public const int sourcesdelay = 5053;

			/// <summary>PID: 5054 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int sourcesgainlow_5054 = 5054;

			/// <summary>PID: 5054 | Type: write</summary>
			public const int sourcesgainlow = 5054;

			/// <summary>PID: 5055 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int sourcesgainhigh_5055 = 5055;

			/// <summary>PID: 5055 | Type: write</summary>
			public const int sourcesgainhigh = 5055;

			/// <summary>PID: 5056 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int sourcesmute_5056 = 5056;

			/// <summary>PID: 5056 | Type: write</summary>
			public const int sourcesmute = 5056;

			/// <summary>PID: 5057 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int sourcesphase_5057 = 5057;

			/// <summary>PID: 5057 | Type: write</summary>
			public const int sourcesphase = 5057;

			/// <summary>PID: 5203 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int destinationsconnectedsourcenumber_5203 = 5203;

			/// <summary>PID: 5203 | Type: write</summary>
			public const int destinationsconnectedsourcenumber = 5203;

			/// <summary>PID: 5205 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int destinationsprotectstatus_5205 = 5205;

			/// <summary>PID: 5205 | Type: write</summary>
			public const int destinationsprotectstatus = 5205;

			/// <summary>PID: 5206 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int destinationsdelay_5206 = 5206;

			/// <summary>PID: 5206 | Type: write</summary>
			public const int destinationsdelay = 5206;

			/// <summary>PID: 5207 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int destinationsgainlow_5207 = 5207;

			/// <summary>PID: 5207 | Type: write</summary>
			public const int destinationsgainlow = 5207;

			/// <summary>PID: 5208 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int destinationsgainhigh_5208 = 5208;

			/// <summary>PID: 5208 | Type: write</summary>
			public const int destinationsgainhigh = 5208;

			/// <summary>PID: 5209 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int destinationsmute_5209 = 5209;

			/// <summary>PID: 5209 | Type: write</summary>
			public const int destinationsmute = 5209;

			/// <summary>PID: 5210 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int destinationsphase_5210 = 5210;

			/// <summary>PID: 5210 | Type: write</summary>
			public const int destinationsphase = 5210;
		}

		public class Sources
		{
			/// <summary>PID: 5000</summary>
			public const int tablePid = 5000;

			/// <summary>IDX: 0</summary>
			public const int indexColumn = 0;

			/// <summary>PID: 5001</summary>
			public const int indexColumnPid = 5001;

			public class Pid
			{
				/// <summary>PID: 5001 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sourcesnumber_5001 = 5001;

				/// <summary>PID: 5001 | Type: read</summary>
				public const int sourcesnumber = 5001;

				/// <summary>PID: 5002 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sourceslabel_5002 = 5002;

				/// <summary>PID: 5002 | Type: read</summary>
				public const int sourceslabel = 5002;

				/// <summary>PID: 5003 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sourcesdelay_5003 = 5003;

				/// <summary>PID: 5003 | Type: read</summary>
				public const int sourcesdelay = 5003;

				/// <summary>PID: 5004 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sourcesgainlow_5004 = 5004;

				/// <summary>PID: 5004 | Type: read</summary>
				public const int sourcesgainlow = 5004;

				/// <summary>PID: 5005 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sourcesgainhigh_5005 = 5005;

				/// <summary>PID: 5005 | Type: read</summary>
				public const int sourcesgainhigh = 5005;

				/// <summary>PID: 5006 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sourcesmute_5006 = 5006;

				/// <summary>PID: 5006 | Type: read</summary>
				public const int sourcesmute = 5006;

				/// <summary>PID: 5007 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sourcesphase_5007 = 5007;

				/// <summary>PID: 5007 | Type: read</summary>
				public const int sourcesphase = 5007;

				public class Write
				{
				}
			}

			public class Idx
			{
				/// <summary>IDX: 0 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sourcesnumber_5001 = 0;

				/// <summary>IDX: 0 | Type: read</summary>
				public const int sourcesnumber = 0;

				/// <summary>IDX: 1 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sourceslabel_5002 = 1;

				/// <summary>IDX: 1 | Type: read</summary>
				public const int sourceslabel = 1;

				/// <summary>IDX: 2 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sourcesdelay_5003 = 2;

				/// <summary>IDX: 2 | Type: read</summary>
				public const int sourcesdelay = 2;

				/// <summary>IDX: 3 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sourcesgainlow_5004 = 3;

				/// <summary>IDX: 3 | Type: read</summary>
				public const int sourcesgainlow = 3;

				/// <summary>IDX: 4 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sourcesgainhigh_5005 = 4;

				/// <summary>IDX: 4 | Type: read</summary>
				public const int sourcesgainhigh = 4;

				/// <summary>IDX: 5 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sourcesmute_5006 = 5;

				/// <summary>IDX: 5 | Type: read</summary>
				public const int sourcesmute = 5;

				/// <summary>IDX: 6 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sourcesphase_5007 = 6;

				/// <summary>IDX: 6 | Type: read</summary>
				public const int sourcesphase = 6;
			}
		}

		public class Destinations
		{
			/// <summary>PID: 5100</summary>
			public const int tablePid = 5100;

			/// <summary>IDX: 0</summary>
			public const int indexColumn = 0;

			/// <summary>PID: 5101</summary>
			public const int indexColumnPid = 5101;

			public class Pid
			{
				/// <summary>PID: 5101 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsnumber_5101 = 5101;

				/// <summary>PID: 5101 | Type: read</summary>
				public const int destinationsnumber = 5101;

				/// <summary>PID: 5102 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationslabel_5102 = 5102;

				/// <summary>PID: 5102 | Type: read</summary>
				public const int destinationslabel = 5102;

				/// <summary>PID: 5103 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsconnectedsourcenumber_5103 = 5103;

				/// <summary>PID: 5103 | Type: read</summary>
				public const int destinationsconnectedsourcenumber = 5103;

				/// <summary>PID: 5104 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsassociationname_5104 = 5104;

				/// <summary>PID: 5104 | Type: read</summary>
				public const int destinationsassociationname = 5104;

				/// <summary>PID: 5105 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsprotectstatus_5105 = 5105;

				/// <summary>PID: 5105 | Type: read</summary>
				public const int destinationsprotectstatus = 5105;

				/// <summary>PID: 5106 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsdelay_5106 = 5106;

				/// <summary>PID: 5106 | Type: read</summary>
				public const int destinationsdelay = 5106;

				/// <summary>PID: 5107 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsgainlow_5107 = 5107;

				/// <summary>PID: 5107 | Type: read</summary>
				public const int destinationsgainlow = 5107;

				/// <summary>PID: 5108 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsgainhigh_5108 = 5108;

				/// <summary>PID: 5108 | Type: read</summary>
				public const int destinationsgainhigh = 5108;

				/// <summary>PID: 5109 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsmute_5109 = 5109;

				/// <summary>PID: 5109 | Type: read</summary>
				public const int destinationsmute = 5109;

				/// <summary>PID: 5110 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsphase_5110 = 5110;

				/// <summary>PID: 5110 | Type: read</summary>
				public const int destinationsphase = 5110;

				public class Write
				{
				}
			}

			public class Idx
			{
				/// <summary>IDX: 0 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsnumber_5101 = 0;

				/// <summary>IDX: 0 | Type: read</summary>
				public const int destinationsnumber = 0;

				/// <summary>IDX: 1 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationslabel_5102 = 1;

				/// <summary>IDX: 1 | Type: read</summary>
				public const int destinationslabel = 1;

				/// <summary>IDX: 2 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsconnectedsourcenumber_5103 = 2;

				/// <summary>IDX: 2 | Type: read</summary>
				public const int destinationsconnectedsourcenumber = 2;

				/// <summary>IDX: 3 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsassociationname_5104 = 3;

				/// <summary>IDX: 3 | Type: read</summary>
				public const int destinationsassociationname = 3;

				/// <summary>IDX: 4 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsprotectstatus_5105 = 4;

				/// <summary>IDX: 4 | Type: read</summary>
				public const int destinationsprotectstatus = 4;

				/// <summary>IDX: 5 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsdelay_5106 = 5;

				/// <summary>IDX: 5 | Type: read</summary>
				public const int destinationsdelay = 5;

				/// <summary>IDX: 6 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsgainlow_5107 = 6;

				/// <summary>IDX: 6 | Type: read</summary>
				public const int destinationsgainlow = 6;

				/// <summary>IDX: 7 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsgainhigh_5108 = 7;

				/// <summary>IDX: 7 | Type: read</summary>
				public const int destinationsgainhigh = 7;

				/// <summary>IDX: 8 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsmute_5109 = 8;

				/// <summary>IDX: 8 | Type: read</summary>
				public const int destinationsmute = 8;

				/// <summary>IDX: 9 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int destinationsphase_5110 = 9;

				/// <summary>IDX: 9 | Type: read</summary>
				public const int destinationsphase = 9;
			}
		}
	}

	/// <summary>IDX: 0</summary>
	public class SourcesQActionRow : QActionTableRow
	{
		/// <summary>PID: 5001 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public object Sourcesnumber_5001
		{
			get
			{
				if (base.Columns.ContainsKey(0))
				{
					return base.Columns[0];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(0))
				{
					base.Columns[0] = value;
				}
				else
				{
					base.Columns.Add(0, value);
				}
			}
		}

		/// <summary>PID: 5001 | Type: read</summary>
		public object Sourcesnumber
		{
			get
			{
				if (base.Columns.ContainsKey(0))
				{
					return base.Columns[0];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(0))
				{
					base.Columns[0] = value;
				}
				else
				{
					base.Columns.Add(0, value);
				}
			}
		}

		/// <summary>PID: 5002 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public object Sourceslabel_5002
		{
			get
			{
				if (base.Columns.ContainsKey(1))
				{
					return base.Columns[1];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(1))
				{
					base.Columns[1] = value;
				}
				else
				{
					base.Columns.Add(1, value);
				}
			}
		}

		/// <summary>PID: 5002 | Type: read</summary>
		public object Sourceslabel
		{
			get
			{
				if (base.Columns.ContainsKey(1))
				{
					return base.Columns[1];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(1))
				{
					base.Columns[1] = value;
				}
				else
				{
					base.Columns.Add(1, value);
				}
			}
		}

		/// <summary>PID: 5003 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public object Sourcesdelay_5003
		{
			get
			{
				if (base.Columns.ContainsKey(2))
				{
					return base.Columns[2];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(2))
				{
					base.Columns[2] = value;
				}
				else
				{
					base.Columns.Add(2, value);
				}
			}
		}

		/// <summary>PID: 5003 | Type: read</summary>
		public object Sourcesdelay
		{
			get
			{
				if (base.Columns.ContainsKey(2))
				{
					return base.Columns[2];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(2))
				{
					base.Columns[2] = value;
				}
				else
				{
					base.Columns.Add(2, value);
				}
			}
		}

		/// <summary>PID: 5004 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public object Sourcesgainlow_5004
		{
			get
			{
				if (base.Columns.ContainsKey(3))
				{
					return base.Columns[3];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(3))
				{
					base.Columns[3] = value;
				}
				else
				{
					base.Columns.Add(3, value);
				}
			}
		}

		/// <summary>PID: 5004 | Type: read</summary>
		public object Sourcesgainlow
		{
			get
			{
				if (base.Columns.ContainsKey(3))
				{
					return base.Columns[3];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(3))
				{
					base.Columns[3] = value;
				}
				else
				{
					base.Columns.Add(3, value);
				}
			}
		}

		/// <summary>PID: 5005 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public object Sourcesgainhigh_5005
		{
			get
			{
				if (base.Columns.ContainsKey(4))
				{
					return base.Columns[4];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(4))
				{
					base.Columns[4] = value;
				}
				else
				{
					base.Columns.Add(4, value);
				}
			}
		}

		/// <summary>PID: 5005 | Type: read</summary>
		public object Sourcesgainhigh
		{
			get
			{
				if (base.Columns.ContainsKey(4))
				{
					return base.Columns[4];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(4))
				{
					base.Columns[4] = value;
				}
				else
				{
					base.Columns.Add(4, value);
				}
			}
		}

		/// <summary>PID: 5006 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public object Sourcesmute_5006
		{
			get
			{
				if (base.Columns.ContainsKey(5))
				{
					return base.Columns[5];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(5))
				{
					base.Columns[5] = value;
				}
				else
				{
					base.Columns.Add(5, value);
				}
			}
		}

		/// <summary>PID: 5006 | Type: read</summary>
		public object Sourcesmute
		{
			get
			{
				if (base.Columns.ContainsKey(5))
				{
					return base.Columns[5];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(5))
				{
					base.Columns[5] = value;
				}
				else
				{
					base.Columns.Add(5, value);
				}
			}
		}

		/// <summary>PID: 5007 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public object Sourcesphase_5007
		{
			get
			{
				if (base.Columns.ContainsKey(6))
				{
					return base.Columns[6];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(6))
				{
					base.Columns[6] = value;
				}
				else
				{
					base.Columns.Add(6, value);
				}
			}
		}

		/// <summary>PID: 5007 | Type: read</summary>
		public object Sourcesphase
		{
			get
			{
				if (base.Columns.ContainsKey(6))
				{
					return base.Columns[6];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(6))
				{
					base.Columns[6] = value;
				}
				else
				{
					base.Columns.Add(6, value);
				}
			}
		}

		public SourcesQActionRow() : base(0, 7)
		{
		}

		public SourcesQActionRow(object[] oRow) : base(0, 7, oRow)
		{
		}

		public static implicit operator SourcesQActionRow(object[] source)
		{
			return new SourcesQActionRow(source);
		}

		public static implicit operator object[](SourcesQActionRow source)
		{
			return source.ToObjectArray();
		}
	}

	/// <summary>IDX: 0</summary>
	public class DestinationsQActionRow : QActionTableRow
	{
		/// <summary>PID: 5101 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public object Destinationsnumber_5101
		{
			get
			{
				if (base.Columns.ContainsKey(0))
				{
					return base.Columns[0];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(0))
				{
					base.Columns[0] = value;
				}
				else
				{
					base.Columns.Add(0, value);
				}
			}
		}

		/// <summary>PID: 5101 | Type: read</summary>
		public object Destinationsnumber
		{
			get
			{
				if (base.Columns.ContainsKey(0))
				{
					return base.Columns[0];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(0))
				{
					base.Columns[0] = value;
				}
				else
				{
					base.Columns.Add(0, value);
				}
			}
		}

		/// <summary>PID: 5102 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public object Destinationslabel_5102
		{
			get
			{
				if (base.Columns.ContainsKey(1))
				{
					return base.Columns[1];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(1))
				{
					base.Columns[1] = value;
				}
				else
				{
					base.Columns.Add(1, value);
				}
			}
		}

		/// <summary>PID: 5102 | Type: read</summary>
		public object Destinationslabel
		{
			get
			{
				if (base.Columns.ContainsKey(1))
				{
					return base.Columns[1];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(1))
				{
					base.Columns[1] = value;
				}
				else
				{
					base.Columns.Add(1, value);
				}
			}
		}

		/// <summary>PID: 5103 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public object Destinationsconnectedsourcenumber_5103
		{
			get
			{
				if (base.Columns.ContainsKey(2))
				{
					return base.Columns[2];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(2))
				{
					base.Columns[2] = value;
				}
				else
				{
					base.Columns.Add(2, value);
				}
			}
		}

		/// <summary>PID: 5103 | Type: read</summary>
		public object Destinationsconnectedsourcenumber
		{
			get
			{
				if (base.Columns.ContainsKey(2))
				{
					return base.Columns[2];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(2))
				{
					base.Columns[2] = value;
				}
				else
				{
					base.Columns.Add(2, value);
				}
			}
		}

		/// <summary>PID: 5104 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public object Destinationsassociationname_5104
		{
			get
			{
				if (base.Columns.ContainsKey(3))
				{
					return base.Columns[3];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(3))
				{
					base.Columns[3] = value;
				}
				else
				{
					base.Columns.Add(3, value);
				}
			}
		}

		/// <summary>PID: 5104 | Type: read</summary>
		public object Destinationsassociationname
		{
			get
			{
				if (base.Columns.ContainsKey(3))
				{
					return base.Columns[3];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(3))
				{
					base.Columns[3] = value;
				}
				else
				{
					base.Columns.Add(3, value);
				}
			}
		}

		/// <summary>PID: 5105 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public object Destinationsprotectstatus_5105
		{
			get
			{
				if (base.Columns.ContainsKey(4))
				{
					return base.Columns[4];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(4))
				{
					base.Columns[4] = value;
				}
				else
				{
					base.Columns.Add(4, value);
				}
			}
		}

		/// <summary>PID: 5105 | Type: read</summary>
		public object Destinationsprotectstatus
		{
			get
			{
				if (base.Columns.ContainsKey(4))
				{
					return base.Columns[4];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(4))
				{
					base.Columns[4] = value;
				}
				else
				{
					base.Columns.Add(4, value);
				}
			}
		}

		/// <summary>PID: 5106 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public object Destinationsdelay_5106
		{
			get
			{
				if (base.Columns.ContainsKey(5))
				{
					return base.Columns[5];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(5))
				{
					base.Columns[5] = value;
				}
				else
				{
					base.Columns.Add(5, value);
				}
			}
		}

		/// <summary>PID: 5106 | Type: read</summary>
		public object Destinationsdelay
		{
			get
			{
				if (base.Columns.ContainsKey(5))
				{
					return base.Columns[5];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(5))
				{
					base.Columns[5] = value;
				}
				else
				{
					base.Columns.Add(5, value);
				}
			}
		}

		/// <summary>PID: 5107 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public object Destinationsgainlow_5107
		{
			get
			{
				if (base.Columns.ContainsKey(6))
				{
					return base.Columns[6];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(6))
				{
					base.Columns[6] = value;
				}
				else
				{
					base.Columns.Add(6, value);
				}
			}
		}

		/// <summary>PID: 5107 | Type: read</summary>
		public object Destinationsgainlow
		{
			get
			{
				if (base.Columns.ContainsKey(6))
				{
					return base.Columns[6];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(6))
				{
					base.Columns[6] = value;
				}
				else
				{
					base.Columns.Add(6, value);
				}
			}
		}

		/// <summary>PID: 5108 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public object Destinationsgainhigh_5108
		{
			get
			{
				if (base.Columns.ContainsKey(7))
				{
					return base.Columns[7];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(7))
				{
					base.Columns[7] = value;
				}
				else
				{
					base.Columns.Add(7, value);
				}
			}
		}

		/// <summary>PID: 5108 | Type: read</summary>
		public object Destinationsgainhigh
		{
			get
			{
				if (base.Columns.ContainsKey(7))
				{
					return base.Columns[7];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(7))
				{
					base.Columns[7] = value;
				}
				else
				{
					base.Columns.Add(7, value);
				}
			}
		}

		/// <summary>PID: 5109 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public object Destinationsmute_5109
		{
			get
			{
				if (base.Columns.ContainsKey(8))
				{
					return base.Columns[8];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(8))
				{
					base.Columns[8] = value;
				}
				else
				{
					base.Columns.Add(8, value);
				}
			}
		}

		/// <summary>PID: 5109 | Type: read</summary>
		public object Destinationsmute
		{
			get
			{
				if (base.Columns.ContainsKey(8))
				{
					return base.Columns[8];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(8))
				{
					base.Columns[8] = value;
				}
				else
				{
					base.Columns.Add(8, value);
				}
			}
		}

		/// <summary>PID: 5110 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public object Destinationsphase_5110
		{
			get
			{
				if (base.Columns.ContainsKey(9))
				{
					return base.Columns[9];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(9))
				{
					base.Columns[9] = value;
				}
				else
				{
					base.Columns.Add(9, value);
				}
			}
		}

		/// <summary>PID: 5110 | Type: read</summary>
		public object Destinationsphase
		{
			get
			{
				if (base.Columns.ContainsKey(9))
				{
					return base.Columns[9];
				}
				else
				{
					return null;
				}
			}

			set
			{
				if (base.Columns.ContainsKey(9))
				{
					base.Columns[9] = value;
				}
				else
				{
					base.Columns.Add(9, value);
				}
			}
		}

		public DestinationsQActionRow() : base(0, 10)
		{
		}

		public DestinationsQActionRow(object[] oRow) : base(0, 10, oRow)
		{
		}

		public static implicit operator DestinationsQActionRow(object[] source)
		{
			return new DestinationsQActionRow(source);
		}

		public static implicit operator object[](DestinationsQActionRow source)
		{
			return source.ToObjectArray();
		}
	}
}