// <auto-generated/>
namespace Generate_Flows_1.AMWA_NMOS_IS_05
{
	using System.ComponentModel;
	using Generate_Flows_1.QActionHelpers;

	public static class Parameter
	{
		/// <summary>PID: 29 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int responsecontentpollnodeself_29 = 29;
		/// <summary>PID: 29 | Type: read</summary>
		public const int responsecontentpollnodeself = 29;
		/// <summary>PID: 30 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int responsecode_30 = 30;
		/// <summary>PID: 30 | Type: read</summary>
		public const int responsecode = 30;
		/// <summary>PID: 31 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int responsecontentpollreceivers_31 = 31;
		/// <summary>PID: 31 | Type: read</summary>
		public const int responsecontentpollreceivers = 31;
		/// <summary>PID: 32 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int urlpollsinglereceiver_32 = 32;
		/// <summary>PID: 32 | Type: read</summary>
		public const int urlpollsinglereceiver = 32;
		/// <summary>PID: 33 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int responsecontentpollsinglereceiver_33 = 33;
		/// <summary>PID: 33 | Type: read</summary>
		public const int responsecontentpollsinglereceiver = 33;
		/// <summary>PID: 34 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int queuesinglereceivers_34 = 34;
		/// <summary>PID: 34 | Type: read</summary>
		public const int queuesinglereceivers = 34;
		/// <summary>PID: 35 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int pollingongoing_35 = 35;
		/// <summary>PID: 35 | Type: read</summary>
		public const int pollingongoing = 35;
		/// <summary>PID: 36 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int startpollcycle_36 = 36;
		/// <summary>PID: 36 | Type: read</summary>
		public const int startpollcycle = 36;
		/// <summary>PID: 37 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int urlpatch_37 = 37;
		/// <summary>PID: 37 | Type: read</summary>
		public const int urlpatch = 37;
		/// <summary>PID: 38 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int responsepatch_38 = 38;
		/// <summary>PID: 38 | Type: read</summary>
		public const int responsepatch = 38;
		/// <summary>PID: 39 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int requestpatch_39 = 39;
		/// <summary>PID: 39 | Type: read</summary>
		public const int requestpatch = 39;
		/// <summary>PID: 40 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int responsecontentpollsenders_40 = 40;
		/// <summary>PID: 40 | Type: read</summary>
		public const int responsecontentpollsenders = 40;
		/// <summary>PID: 41 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int queuesinglesenders_41 = 41;
		/// <summary>PID: 41 | Type: read</summary>
		public const int queuesinglesenders = 41;
		/// <summary>PID: 42 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int urlpollsinglesender_42 = 42;
		/// <summary>PID: 42 | Type: read</summary>
		public const int urlpollsinglesender = 42;
		/// <summary>PID: 43 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int responsecontentpollsinglesender_43 = 43;
		/// <summary>PID: 43 | Type: read</summary>
		public const int responsecontentpollsinglesender = 43;
		/// <summary>PID: 44 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int responsecontentpollsendersdata_44 = 44;
		/// <summary>PID: 44 | Type: read</summary>
		public const int responsecontentpollsendersdata = 44;
		/// <summary>PID: 45 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int responsecontentpollreceiversdata_45 = 45;
		/// <summary>PID: 45 | Type: read</summary>
		public const int responsecontentpollreceiversdata = 45;
		/// <summary>PID: 46 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int requestsenderspatch_46 = 46;
		/// <summary>PID: 46 | Type: read</summary>
		public const int requestsenderspatch = 46;
		/// <summary>PID: 47 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int urlpatchsenders_47 = 47;
		/// <summary>PID: 47 | Type: read</summary>
		public const int urlpatchsenders = 47;
		/// <summary>PID: 48 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int responsepatchsenders_48 = 48;
		/// <summary>PID: 48 | Type: read</summary>
		public const int responsepatchsenders = 48;
		/// <summary>PID: 49 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int urlpollsendertransportfile_49 = 49;
		/// <summary>PID: 49 | Type: read</summary>
		public const int urlpollsendertransportfile = 49;
		/// <summary>PID: 50 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int responsecontentpollsendertransportfile_50 = 50;
		/// <summary>PID: 50 | Type: read</summary>
		public const int responsecontentpollsendertransportfile = 50;
		/// <summary>PID: 9000000 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int clp_interapp_receive_9000000 = 9000000;
		/// <summary>PID: 9000000 | Type: read</summary>
		public const int clp_interapp_receive = 9000000;
		/// <summary>PID: 9000001 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int clp_interapp_return_9000001 = 9000001;
		/// <summary>PID: 9000001 | Type: read</summary>
		public const int clp_interapp_return = 9000001;
		public class Write
		{
			/// <summary>PID: 154 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int receiverstransportparamsprimarysourceip_154 = 154;
			/// <summary>PID: 154 | Type: write</summary>
			public const int receiverstransportparamsprimarysourceip = 154;
			/// <summary>PID: 155 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int receiverstransportparamsprimarymulticastip_155 = 155;
			/// <summary>PID: 155 | Type: write</summary>
			public const int receiverstransportparamsprimarymulticastip = 155;
			/// <summary>PID: 156 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int receiverstransportparamsprimarydestinationport_156 = 156;
			/// <summary>PID: 156 | Type: write</summary>
			public const int receiverstransportparamsprimarydestinationport = 156;
			/// <summary>PID: 157 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int receiverstransportparamsprimaryinterfaceip_157 = 157;
			/// <summary>PID: 157 | Type: write</summary>
			public const int receiverstransportparamsprimaryinterfaceip = 157;
			/// <summary>PID: 159 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int receiverstransportparamssecondarysourceip_159 = 159;
			/// <summary>PID: 159 | Type: write</summary>
			public const int receiverstransportparamssecondarysourceip = 159;
			/// <summary>PID: 160 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int receiverstransportparamssecondarymulticastip_160 = 160;
			/// <summary>PID: 160 | Type: write</summary>
			public const int receiverstransportparamssecondarymulticastip = 160;
			/// <summary>PID: 161 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int receiverstransportparamssecondarydestinationport_161 = 161;
			/// <summary>PID: 161 | Type: write</summary>
			public const int receiverstransportparamssecondarydestinationport = 161;
			/// <summary>PID: 162 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int receiverstransportparamssecondaryinterfaceip_162 = 162;
			/// <summary>PID: 162 | Type: write</summary>
			public const int receiverstransportparamssecondaryinterfaceip = 162;
			/// <summary>PID: 354 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int senderstransportparamsprimarysourceip_354 = 354;
			/// <summary>PID: 354 | Type: write</summary>
			public const int senderstransportparamsprimarysourceip = 354;
			/// <summary>PID: 355 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int senderstransportparamsprimarysourceport_355 = 355;
			/// <summary>PID: 355 | Type: write</summary>
			public const int senderstransportparamsprimarysourceport = 355;
			/// <summary>PID: 356 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int senderstransportparamsprimarydestinationport_356 = 356;
			/// <summary>PID: 356 | Type: write</summary>
			public const int senderstransportparamsprimarydestinationport = 356;
			/// <summary>PID: 357 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int senderstransportparamsprimarydestinationip_357 = 357;
			/// <summary>PID: 357 | Type: write</summary>
			public const int senderstransportparamsprimarydestinationip = 357;
			/// <summary>PID: 359 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int senderstransportparamssecondarysourceip_359 = 359;
			/// <summary>PID: 359 | Type: write</summary>
			public const int senderstransportparamssecondarysourceip = 359;
			/// <summary>PID: 360 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int senderstransportparamssecondarysourceport_360 = 360;
			/// <summary>PID: 360 | Type: write</summary>
			public const int senderstransportparamssecondarysourceport = 360;
			/// <summary>PID: 361 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int senderstransportparamssecondarydestinationport_361 = 361;
			/// <summary>PID: 361 | Type: write</summary>
			public const int senderstransportparamssecondarydestinationport = 361;
			/// <summary>PID: 362 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int senderstransportparamssecondarydestinationip_362 = 362;
			/// <summary>PID: 362 | Type: write</summary>
			public const int senderstransportparamssecondarydestinationip = 362;
		}
		public class Receivers
		{
			/// <summary>PID: 100</summary>
			public const int tablePid = 100;
			/// <summary>IDX: 0</summary>
			public const int indexColumn = 0;
			/// <summary>PID: 101</summary>
			public const int indexColumnPid = 101;
			public class Pid
			{
				/// <summary>PID: 101 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiversid_101 = 101;
				/// <summary>PID: 101 | Type: read</summary>
				public const int receiversid = 101;
				/// <summary>PID: 102 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverssenderid_102 = 102;
				/// <summary>PID: 102 | Type: read</summary>
				public const int receiverssenderid = 102;
				/// <summary>PID: 103 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiversmasterenable_103 = 103;
				/// <summary>PID: 103 | Type: read</summary>
				public const int receiversmasterenable = 103;
				/// <summary>PID: 104 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamsprimarysourceip_104 = 104;
				/// <summary>PID: 104 | Type: read</summary>
				public const int receiverstransportparamsprimarysourceip = 104;
				/// <summary>PID: 105 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamsprimarymulticastip_105 = 105;
				/// <summary>PID: 105 | Type: read</summary>
				public const int receiverstransportparamsprimarymulticastip = 105;
				/// <summary>PID: 106 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamsprimarydestinationport_106 = 106;
				/// <summary>PID: 106 | Type: read</summary>
				public const int receiverstransportparamsprimarydestinationport = 106;
				/// <summary>PID: 107 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamsprimaryinterfaceip_107 = 107;
				/// <summary>PID: 107 | Type: read</summary>
				public const int receiverstransportparamsprimaryinterfaceip = 107;
				/// <summary>PID: 108 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamsprimaryrtpenabled_108 = 108;
				/// <summary>PID: 108 | Type: read</summary>
				public const int receiverstransportparamsprimaryrtpenabled = 108;
				/// <summary>PID: 109 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamssecondarysourceip_109 = 109;
				/// <summary>PID: 109 | Type: read</summary>
				public const int receiverstransportparamssecondarysourceip = 109;
				/// <summary>PID: 110 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamssecondarymulticastip_110 = 110;
				/// <summary>PID: 110 | Type: read</summary>
				public const int receiverstransportparamssecondarymulticastip = 110;
				/// <summary>PID: 111 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamssecondarydestinationport_111 = 111;
				/// <summary>PID: 111 | Type: read</summary>
				public const int receiverstransportparamssecondarydestinationport = 111;
				/// <summary>PID: 112 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamssecondaryinterfaceip_112 = 112;
				/// <summary>PID: 112 | Type: read</summary>
				public const int receiverstransportparamssecondaryinterfaceip = 112;
				/// <summary>PID: 113 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamssecondaryrtpenabled_113 = 113;
				/// <summary>PID: 113 | Type: read</summary>
				public const int receiverstransportparamssecondaryrtpenabled = 113;
				/// <summary>PID: 114 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiversdescription_114 = 114;
				/// <summary>PID: 114 | Type: read</summary>
				public const int receiversdescription = 114;
				/// <summary>PID: 115 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiversdsp_115 = 115;
				/// <summary>PID: 115 | Type: read</summary>
				public const int receiversdsp = 115;
				/// <summary>PID: 116 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiversactivationtime_116 = 116;
				/// <summary>PID: 116 | Type: read</summary>
				public const int receiversactivationtime = 116;
				/// <summary>PID: 117 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverspatchstatus_117 = 117;
				/// <summary>PID: 117 | Type: read</summary>
				public const int receiverspatchstatus = 117;
				/// <summary>PID: 118 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverspatchstatusmessage_118 = 118;
				/// <summary>PID: 118 | Type: read</summary>
				public const int receiverspatchstatusmessage = 118;
				/// <summary>PID: 119 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiversprimaryinterfacebinding_119 = 119;
				/// <summary>PID: 119 | Type: read</summary>
				public const int receiversprimaryinterfacebinding = 119;
				/// <summary>PID: 120 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverssecondaryinterfacebinding_120 = 120;
				/// <summary>PID: 120 | Type: read</summary>
				public const int receiverssecondaryinterfacebinding = 120;
				public class Write
				{
				}
			}
			public class Idx
			{
				/// <summary>IDX: 0 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiversid_101 = 0;
				/// <summary>IDX: 0 | Type: read</summary>
				public const int receiversid = 0;
				/// <summary>IDX: 1 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverssenderid_102 = 1;
				/// <summary>IDX: 1 | Type: read</summary>
				public const int receiverssenderid = 1;
				/// <summary>IDX: 2 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiversmasterenable_103 = 2;
				/// <summary>IDX: 2 | Type: read</summary>
				public const int receiversmasterenable = 2;
				/// <summary>IDX: 3 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamsprimarysourceip_104 = 3;
				/// <summary>IDX: 3 | Type: read</summary>
				public const int receiverstransportparamsprimarysourceip = 3;
				/// <summary>IDX: 4 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamsprimarymulticastip_105 = 4;
				/// <summary>IDX: 4 | Type: read</summary>
				public const int receiverstransportparamsprimarymulticastip = 4;
				/// <summary>IDX: 5 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamsprimarydestinationport_106 = 5;
				/// <summary>IDX: 5 | Type: read</summary>
				public const int receiverstransportparamsprimarydestinationport = 5;
				/// <summary>IDX: 6 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamsprimaryinterfaceip_107 = 6;
				/// <summary>IDX: 6 | Type: read</summary>
				public const int receiverstransportparamsprimaryinterfaceip = 6;
				/// <summary>IDX: 7 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamsprimaryrtpenabled_108 = 7;
				/// <summary>IDX: 7 | Type: read</summary>
				public const int receiverstransportparamsprimaryrtpenabled = 7;
				/// <summary>IDX: 8 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamssecondarysourceip_109 = 8;
				/// <summary>IDX: 8 | Type: read</summary>
				public const int receiverstransportparamssecondarysourceip = 8;
				/// <summary>IDX: 9 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamssecondarymulticastip_110 = 9;
				/// <summary>IDX: 9 | Type: read</summary>
				public const int receiverstransportparamssecondarymulticastip = 9;
				/// <summary>IDX: 10 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamssecondarydestinationport_111 = 10;
				/// <summary>IDX: 10 | Type: read</summary>
				public const int receiverstransportparamssecondarydestinationport = 10;
				/// <summary>IDX: 11 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamssecondaryinterfaceip_112 = 11;
				/// <summary>IDX: 11 | Type: read</summary>
				public const int receiverstransportparamssecondaryinterfaceip = 11;
				/// <summary>IDX: 12 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverstransportparamssecondaryrtpenabled_113 = 12;
				/// <summary>IDX: 12 | Type: read</summary>
				public const int receiverstransportparamssecondaryrtpenabled = 12;
				/// <summary>IDX: 13 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiversdescription_114 = 13;
				/// <summary>IDX: 13 | Type: read</summary>
				public const int receiversdescription = 13;
				/// <summary>IDX: 14 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiversdsp_115 = 14;
				/// <summary>IDX: 14 | Type: read</summary>
				public const int receiversdsp = 14;
				/// <summary>IDX: 15 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiversactivationtime_116 = 15;
				/// <summary>IDX: 15 | Type: read</summary>
				public const int receiversactivationtime = 15;
				/// <summary>IDX: 16 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverspatchstatus_117 = 16;
				/// <summary>IDX: 16 | Type: read</summary>
				public const int receiverspatchstatus = 16;
				/// <summary>IDX: 17 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverspatchstatusmessage_118 = 17;
				/// <summary>IDX: 17 | Type: read</summary>
				public const int receiverspatchstatusmessage = 17;
				/// <summary>IDX: 18 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiversprimaryinterfacebinding_119 = 18;
				/// <summary>IDX: 18 | Type: read</summary>
				public const int receiversprimaryinterfacebinding = 18;
				/// <summary>IDX: 19 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int receiverssecondaryinterfacebinding_120 = 19;
				/// <summary>IDX: 19 | Type: read</summary>
				public const int receiverssecondaryinterfacebinding = 19;
			}
		}
		public class Interfaces
		{
			/// <summary>PID: 200</summary>
			public const int tablePid = 200;
			/// <summary>IDX: 0</summary>
			public const int indexColumn = 0;
			/// <summary>PID: 201</summary>
			public const int indexColumnPid = 201;
			public class Pid
			{
				/// <summary>PID: 201 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int interfacesname_201 = 201;
				/// <summary>PID: 201 | Type: read</summary>
				public const int interfacesname = 201;
				/// <summary>PID: 202 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int interfaceschassisid_202 = 202;
				/// <summary>PID: 202 | Type: read</summary>
				public const int interfaceschassisid = 202;
				/// <summary>PID: 203 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int interfacesportid_203 = 203;
				/// <summary>PID: 203 | Type: read</summary>
				public const int interfacesportid = 203;
				public class Write
				{
				}
			}
			public class Idx
			{
				/// <summary>IDX: 0 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int interfacesname_201 = 0;
				/// <summary>IDX: 0 | Type: read</summary>
				public const int interfacesname = 0;
				/// <summary>IDX: 1 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int interfaceschassisid_202 = 1;
				/// <summary>IDX: 1 | Type: read</summary>
				public const int interfaceschassisid = 1;
				/// <summary>IDX: 2 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int interfacesportid_203 = 2;
				/// <summary>IDX: 2 | Type: read</summary>
				public const int interfacesportid = 2;
			}
		}
		public class Senders
		{
			/// <summary>PID: 300</summary>
			public const int tablePid = 300;
			/// <summary>IDX: 0</summary>
			public const int indexColumn = 0;
			/// <summary>PID: 301</summary>
			public const int indexColumnPid = 301;
			public class Pid
			{
				/// <summary>PID: 301 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sendersid_301 = 301;
				/// <summary>PID: 301 | Type: read</summary>
				public const int sendersid = 301;
				/// <summary>PID: 302 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sendersreceiverid_302 = 302;
				/// <summary>PID: 302 | Type: read</summary>
				public const int sendersreceiverid = 302;
				/// <summary>PID: 303 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sendersmasterenable_303 = 303;
				/// <summary>PID: 303 | Type: read</summary>
				public const int sendersmasterenable = 303;
				/// <summary>PID: 304 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamsprimarysourceip_304 = 304;
				/// <summary>PID: 304 | Type: read</summary>
				public const int senderstransportparamsprimarysourceip = 304;
				/// <summary>PID: 305 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamsprimarysourceport_305 = 305;
				/// <summary>PID: 305 | Type: read</summary>
				public const int senderstransportparamsprimarysourceport = 305;
				/// <summary>PID: 306 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamsprimarydestinationport_306 = 306;
				/// <summary>PID: 306 | Type: read</summary>
				public const int senderstransportparamsprimarydestinationport = 306;
				/// <summary>PID: 307 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamsprimarydestinationip_307 = 307;
				/// <summary>PID: 307 | Type: read</summary>
				public const int senderstransportparamsprimarydestinationip = 307;
				/// <summary>PID: 308 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamsprimaryrtpenabled_308 = 308;
				/// <summary>PID: 308 | Type: read</summary>
				public const int senderstransportparamsprimaryrtpenabled = 308;
				/// <summary>PID: 309 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamssecondarysourceip_309 = 309;
				/// <summary>PID: 309 | Type: read</summary>
				public const int senderstransportparamssecondarysourceip = 309;
				/// <summary>PID: 310 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamssecondarysourceport_310 = 310;
				/// <summary>PID: 310 | Type: read</summary>
				public const int senderstransportparamssecondarysourceport = 310;
				/// <summary>PID: 311 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamssecondarydestinationport_311 = 311;
				/// <summary>PID: 311 | Type: read</summary>
				public const int senderstransportparamssecondarydestinationport = 311;
				/// <summary>PID: 312 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamssecondarydestinationip_312 = 312;
				/// <summary>PID: 312 | Type: read</summary>
				public const int senderstransportparamssecondarydestinationip = 312;
				/// <summary>PID: 313 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamssecondaryrtpenabled_313 = 313;
				/// <summary>PID: 313 | Type: read</summary>
				public const int senderstransportparamssecondaryrtpenabled = 313;
				/// <summary>PID: 314 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sendersdescription_314 = 314;
				/// <summary>PID: 314 | Type: read</summary>
				public const int sendersdescription = 314;
				/// <summary>PID: 315 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderssdpfile_string_315 = 315;
				/// <summary>PID: 315 | Type: read</summary>
				public const int senderssdpfile_string = 315;
				/// <summary>PID: 316 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderssdpfile_url_316 = 316;
				/// <summary>PID: 316 | Type: read</summary>
				public const int senderssdpfile_url = 316;
				/// <summary>PID: 317 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sendersactivationtime_317 = 317;
				/// <summary>PID: 317 | Type: read</summary>
				public const int sendersactivationtime = 317;
				/// <summary>PID: 318 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sendersprimaryinterfacebinding_318 = 318;
				/// <summary>PID: 318 | Type: read</summary>
				public const int sendersprimaryinterfacebinding = 318;
				/// <summary>PID: 319 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderssecondaryinterfacebinding_319 = 319;
				/// <summary>PID: 319 | Type: read</summary>
				public const int senderssecondaryinterfacebinding = 319;
				public class Write
				{
				}
			}
			public class Idx
			{
				/// <summary>IDX: 0 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sendersid_301 = 0;
				/// <summary>IDX: 0 | Type: read</summary>
				public const int sendersid = 0;
				/// <summary>IDX: 1 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sendersreceiverid_302 = 1;
				/// <summary>IDX: 1 | Type: read</summary>
				public const int sendersreceiverid = 1;
				/// <summary>IDX: 2 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sendersmasterenable_303 = 2;
				/// <summary>IDX: 2 | Type: read</summary>
				public const int sendersmasterenable = 2;
				/// <summary>IDX: 3 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamsprimarysourceip_304 = 3;
				/// <summary>IDX: 3 | Type: read</summary>
				public const int senderstransportparamsprimarysourceip = 3;
				/// <summary>IDX: 4 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamsprimarysourceport_305 = 4;
				/// <summary>IDX: 4 | Type: read</summary>
				public const int senderstransportparamsprimarysourceport = 4;
				/// <summary>IDX: 5 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamsprimarydestinationport_306 = 5;
				/// <summary>IDX: 5 | Type: read</summary>
				public const int senderstransportparamsprimarydestinationport = 5;
				/// <summary>IDX: 6 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamsprimarydestinationip_307 = 6;
				/// <summary>IDX: 6 | Type: read</summary>
				public const int senderstransportparamsprimarydestinationip = 6;
				/// <summary>IDX: 7 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamsprimaryrtpenabled_308 = 7;
				/// <summary>IDX: 7 | Type: read</summary>
				public const int senderstransportparamsprimaryrtpenabled = 7;
				/// <summary>IDX: 8 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamssecondarysourceip_309 = 8;
				/// <summary>IDX: 8 | Type: read</summary>
				public const int senderstransportparamssecondarysourceip = 8;
				/// <summary>IDX: 9 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamssecondarysourceport_310 = 9;
				/// <summary>IDX: 9 | Type: read</summary>
				public const int senderstransportparamssecondarysourceport = 9;
				/// <summary>IDX: 10 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamssecondarydestinationport_311 = 10;
				/// <summary>IDX: 10 | Type: read</summary>
				public const int senderstransportparamssecondarydestinationport = 10;
				/// <summary>IDX: 11 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamssecondarydestinationip_312 = 11;
				/// <summary>IDX: 11 | Type: read</summary>
				public const int senderstransportparamssecondarydestinationip = 11;
				/// <summary>IDX: 12 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderstransportparamssecondaryrtpenabled_313 = 12;
				/// <summary>IDX: 12 | Type: read</summary>
				public const int senderstransportparamssecondaryrtpenabled = 12;
				/// <summary>IDX: 13 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sendersdescription_314 = 13;
				/// <summary>IDX: 13 | Type: read</summary>
				public const int sendersdescription = 13;
				/// <summary>IDX: 14 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderssdpfile_string_315 = 14;
				/// <summary>IDX: 14 | Type: read</summary>
				public const int senderssdpfile_string = 14;
				/// <summary>IDX: 15 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderssdpfile_url_316 = 15;
				/// <summary>IDX: 15 | Type: read</summary>
				public const int senderssdpfile_url = 15;
				/// <summary>IDX: 16 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sendersactivationtime_317 = 16;
				/// <summary>IDX: 16 | Type: read</summary>
				public const int sendersactivationtime = 16;
				/// <summary>IDX: 17 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int sendersprimaryinterfacebinding_318 = 17;
				/// <summary>IDX: 17 | Type: read</summary>
				public const int sendersprimaryinterfacebinding = 17;
				/// <summary>IDX: 18 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int senderssecondaryinterfacebinding_319 = 18;
				/// <summary>IDX: 18 | Type: read</summary>
				public const int senderssecondaryinterfacebinding = 18;
			}
		}
	}

	/// <summary>IDX: 0</summary>
	public class ReceiversQActionRow : QActionTableRow
	{
		/// <summary>PID: 101 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiversid_101 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
		/// <summary>PID: 101 | Type: read</summary>
		public System.Object Receiversid { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
		/// <summary>PID: 102 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiverssenderid_102 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
		/// <summary>PID: 102 | Type: read</summary>
		public System.Object Receiverssenderid { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
		/// <summary>PID: 103 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiversmasterenable_103 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
		/// <summary>PID: 103 | Type: read</summary>
		public System.Object Receiversmasterenable { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
		/// <summary>PID: 104 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiverstransportparamsprimarysourceip_104 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
		/// <summary>PID: 104 | Type: read</summary>
		public System.Object Receiverstransportparamsprimarysourceip { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
		/// <summary>PID: 105 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiverstransportparamsprimarymulticastip_105 { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
		/// <summary>PID: 105 | Type: read</summary>
		public System.Object Receiverstransportparamsprimarymulticastip { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
		/// <summary>PID: 106 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiverstransportparamsprimarydestinationport_106 { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
		/// <summary>PID: 106 | Type: read</summary>
		public System.Object Receiverstransportparamsprimarydestinationport { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
		/// <summary>PID: 107 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiverstransportparamsprimaryinterfaceip_107 { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
		/// <summary>PID: 107 | Type: read</summary>
		public System.Object Receiverstransportparamsprimaryinterfaceip { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
		/// <summary>PID: 108 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiverstransportparamsprimaryrtpenabled_108 { get { if (base.Columns.ContainsKey(7)) { return base.Columns[7]; } else { return null; } } set { if (base.Columns.ContainsKey(7)) { base.Columns[7] = value; } else { base.Columns.Add(7, value); } } }
		/// <summary>PID: 108 | Type: read</summary>
		public System.Object Receiverstransportparamsprimaryrtpenabled { get { if (base.Columns.ContainsKey(7)) { return base.Columns[7]; } else { return null; } } set { if (base.Columns.ContainsKey(7)) { base.Columns[7] = value; } else { base.Columns.Add(7, value); } } }
		/// <summary>PID: 109 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiverstransportparamssecondarysourceip_109 { get { if (base.Columns.ContainsKey(8)) { return base.Columns[8]; } else { return null; } } set { if (base.Columns.ContainsKey(8)) { base.Columns[8] = value; } else { base.Columns.Add(8, value); } } }
		/// <summary>PID: 109 | Type: read</summary>
		public System.Object Receiverstransportparamssecondarysourceip { get { if (base.Columns.ContainsKey(8)) { return base.Columns[8]; } else { return null; } } set { if (base.Columns.ContainsKey(8)) { base.Columns[8] = value; } else { base.Columns.Add(8, value); } } }
		/// <summary>PID: 110 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiverstransportparamssecondarymulticastip_110 { get { if (base.Columns.ContainsKey(9)) { return base.Columns[9]; } else { return null; } } set { if (base.Columns.ContainsKey(9)) { base.Columns[9] = value; } else { base.Columns.Add(9, value); } } }
		/// <summary>PID: 110 | Type: read</summary>
		public System.Object Receiverstransportparamssecondarymulticastip { get { if (base.Columns.ContainsKey(9)) { return base.Columns[9]; } else { return null; } } set { if (base.Columns.ContainsKey(9)) { base.Columns[9] = value; } else { base.Columns.Add(9, value); } } }
		/// <summary>PID: 111 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiverstransportparamssecondarydestinationport_111 { get { if (base.Columns.ContainsKey(10)) { return base.Columns[10]; } else { return null; } } set { if (base.Columns.ContainsKey(10)) { base.Columns[10] = value; } else { base.Columns.Add(10, value); } } }
		/// <summary>PID: 111 | Type: read</summary>
		public System.Object Receiverstransportparamssecondarydestinationport { get { if (base.Columns.ContainsKey(10)) { return base.Columns[10]; } else { return null; } } set { if (base.Columns.ContainsKey(10)) { base.Columns[10] = value; } else { base.Columns.Add(10, value); } } }
		/// <summary>PID: 112 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiverstransportparamssecondaryinterfaceip_112 { get { if (base.Columns.ContainsKey(11)) { return base.Columns[11]; } else { return null; } } set { if (base.Columns.ContainsKey(11)) { base.Columns[11] = value; } else { base.Columns.Add(11, value); } } }
		/// <summary>PID: 112 | Type: read</summary>
		public System.Object Receiverstransportparamssecondaryinterfaceip { get { if (base.Columns.ContainsKey(11)) { return base.Columns[11]; } else { return null; } } set { if (base.Columns.ContainsKey(11)) { base.Columns[11] = value; } else { base.Columns.Add(11, value); } } }
		/// <summary>PID: 113 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiverstransportparamssecondaryrtpenabled_113 { get { if (base.Columns.ContainsKey(12)) { return base.Columns[12]; } else { return null; } } set { if (base.Columns.ContainsKey(12)) { base.Columns[12] = value; } else { base.Columns.Add(12, value); } } }
		/// <summary>PID: 113 | Type: read</summary>
		public System.Object Receiverstransportparamssecondaryrtpenabled { get { if (base.Columns.ContainsKey(12)) { return base.Columns[12]; } else { return null; } } set { if (base.Columns.ContainsKey(12)) { base.Columns[12] = value; } else { base.Columns.Add(12, value); } } }
		/// <summary>PID: 114 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiversdescription_114 { get { if (base.Columns.ContainsKey(13)) { return base.Columns[13]; } else { return null; } } set { if (base.Columns.ContainsKey(13)) { base.Columns[13] = value; } else { base.Columns.Add(13, value); } } }
		/// <summary>PID: 114 | Type: read</summary>
		public System.Object Receiversdescription { get { if (base.Columns.ContainsKey(13)) { return base.Columns[13]; } else { return null; } } set { if (base.Columns.ContainsKey(13)) { base.Columns[13] = value; } else { base.Columns.Add(13, value); } } }
		/// <summary>PID: 115 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiversdsp_115 { get { if (base.Columns.ContainsKey(14)) { return base.Columns[14]; } else { return null; } } set { if (base.Columns.ContainsKey(14)) { base.Columns[14] = value; } else { base.Columns.Add(14, value); } } }
		/// <summary>PID: 115 | Type: read</summary>
		public System.Object Receiversdsp { get { if (base.Columns.ContainsKey(14)) { return base.Columns[14]; } else { return null; } } set { if (base.Columns.ContainsKey(14)) { base.Columns[14] = value; } else { base.Columns.Add(14, value); } } }
		/// <summary>PID: 116 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiversactivationtime_116 { get { if (base.Columns.ContainsKey(15)) { return base.Columns[15]; } else { return null; } } set { if (base.Columns.ContainsKey(15)) { base.Columns[15] = value; } else { base.Columns.Add(15, value); } } }
		/// <summary>PID: 116 | Type: read</summary>
		public System.Object Receiversactivationtime { get { if (base.Columns.ContainsKey(15)) { return base.Columns[15]; } else { return null; } } set { if (base.Columns.ContainsKey(15)) { base.Columns[15] = value; } else { base.Columns.Add(15, value); } } }
		/// <summary>PID: 117 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiverspatchstatus_117 { get { if (base.Columns.ContainsKey(16)) { return base.Columns[16]; } else { return null; } } set { if (base.Columns.ContainsKey(16)) { base.Columns[16] = value; } else { base.Columns.Add(16, value); } } }
		/// <summary>PID: 117 | Type: read</summary>
		public System.Object Receiverspatchstatus { get { if (base.Columns.ContainsKey(16)) { return base.Columns[16]; } else { return null; } } set { if (base.Columns.ContainsKey(16)) { base.Columns[16] = value; } else { base.Columns.Add(16, value); } } }
		/// <summary>PID: 118 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiverspatchstatusmessage_118 { get { if (base.Columns.ContainsKey(17)) { return base.Columns[17]; } else { return null; } } set { if (base.Columns.ContainsKey(17)) { base.Columns[17] = value; } else { base.Columns.Add(17, value); } } }
		/// <summary>PID: 118 | Type: read</summary>
		public System.Object Receiverspatchstatusmessage { get { if (base.Columns.ContainsKey(17)) { return base.Columns[17]; } else { return null; } } set { if (base.Columns.ContainsKey(17)) { base.Columns[17] = value; } else { base.Columns.Add(17, value); } } }
		/// <summary>PID: 119 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiversprimaryinterfacebinding_119 { get { if (base.Columns.ContainsKey(18)) { return base.Columns[18]; } else { return null; } } set { if (base.Columns.ContainsKey(18)) { base.Columns[18] = value; } else { base.Columns.Add(18, value); } } }
		/// <summary>PID: 119 | Type: read</summary>
		public System.Object Receiversprimaryinterfacebinding { get { if (base.Columns.ContainsKey(18)) { return base.Columns[18]; } else { return null; } } set { if (base.Columns.ContainsKey(18)) { base.Columns[18] = value; } else { base.Columns.Add(18, value); } } }
		/// <summary>PID: 120 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Receiverssecondaryinterfacebinding_120 { get { if (base.Columns.ContainsKey(19)) { return base.Columns[19]; } else { return null; } } set { if (base.Columns.ContainsKey(19)) { base.Columns[19] = value; } else { base.Columns.Add(19, value); } } }
		/// <summary>PID: 120 | Type: read</summary>
		public System.Object Receiverssecondaryinterfacebinding { get { if (base.Columns.ContainsKey(19)) { return base.Columns[19]; } else { return null; } } set { if (base.Columns.ContainsKey(19)) { base.Columns[19] = value; } else { base.Columns.Add(19, value); } } }
		public ReceiversQActionRow() : base(0, 20) { }
		public ReceiversQActionRow(System.Object[] oRow) : base(0, 20, oRow) { }
		public static implicit operator ReceiversQActionRow(System.Object[] source) { return new ReceiversQActionRow(source); }
		public static implicit operator System.Object[](ReceiversQActionRow source) { return source.ToObjectArray(); }
	}
	/// <summary>IDX: 0</summary>
	public class InterfacesQActionRow : QActionTableRow
	{
		/// <summary>PID: 201 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Interfacesname_201 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
		/// <summary>PID: 201 | Type: read</summary>
		public System.Object Interfacesname { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
		/// <summary>PID: 202 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Interfaceschassisid_202 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
		/// <summary>PID: 202 | Type: read</summary>
		public System.Object Interfaceschassisid { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
		/// <summary>PID: 203 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Interfacesportid_203 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
		/// <summary>PID: 203 | Type: read</summary>
		public System.Object Interfacesportid { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
		public InterfacesQActionRow() : base(0, 3) { }
		public InterfacesQActionRow(System.Object[] oRow) : base(0, 3, oRow) { }
		public static implicit operator InterfacesQActionRow(System.Object[] source) { return new InterfacesQActionRow(source); }
		public static implicit operator System.Object[](InterfacesQActionRow source) { return source.ToObjectArray(); }
	}
	/// <summary>IDX: 0</summary>
	public class SendersQActionRow : QActionTableRow
	{
		/// <summary>PID: 301 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Sendersid_301 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
		/// <summary>PID: 301 | Type: read</summary>
		public System.Object Sendersid { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
		/// <summary>PID: 302 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Sendersreceiverid_302 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
		/// <summary>PID: 302 | Type: read</summary>
		public System.Object Sendersreceiverid { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
		/// <summary>PID: 303 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Sendersmasterenable_303 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
		/// <summary>PID: 303 | Type: read</summary>
		public System.Object Sendersmasterenable { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
		/// <summary>PID: 304 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Senderstransportparamsprimarysourceip_304 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
		/// <summary>PID: 304 | Type: read</summary>
		public System.Object Senderstransportparamsprimarysourceip { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
		/// <summary>PID: 305 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Senderstransportparamsprimarysourceport_305 { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
		/// <summary>PID: 305 | Type: read</summary>
		public System.Object Senderstransportparamsprimarysourceport { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
		/// <summary>PID: 306 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Senderstransportparamsprimarydestinationport_306 { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
		/// <summary>PID: 306 | Type: read</summary>
		public System.Object Senderstransportparamsprimarydestinationport { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
		/// <summary>PID: 307 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Senderstransportparamsprimarydestinationip_307 { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
		/// <summary>PID: 307 | Type: read</summary>
		public System.Object Senderstransportparamsprimarydestinationip { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
		/// <summary>PID: 308 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Senderstransportparamsprimaryrtpenabled_308 { get { if (base.Columns.ContainsKey(7)) { return base.Columns[7]; } else { return null; } } set { if (base.Columns.ContainsKey(7)) { base.Columns[7] = value; } else { base.Columns.Add(7, value); } } }
		/// <summary>PID: 308 | Type: read</summary>
		public System.Object Senderstransportparamsprimaryrtpenabled { get { if (base.Columns.ContainsKey(7)) { return base.Columns[7]; } else { return null; } } set { if (base.Columns.ContainsKey(7)) { base.Columns[7] = value; } else { base.Columns.Add(7, value); } } }
		/// <summary>PID: 309 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Senderstransportparamssecondarysourceip_309 { get { if (base.Columns.ContainsKey(8)) { return base.Columns[8]; } else { return null; } } set { if (base.Columns.ContainsKey(8)) { base.Columns[8] = value; } else { base.Columns.Add(8, value); } } }
		/// <summary>PID: 309 | Type: read</summary>
		public System.Object Senderstransportparamssecondarysourceip { get { if (base.Columns.ContainsKey(8)) { return base.Columns[8]; } else { return null; } } set { if (base.Columns.ContainsKey(8)) { base.Columns[8] = value; } else { base.Columns.Add(8, value); } } }
		/// <summary>PID: 310 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Senderstransportparamssecondarysourceport_310 { get { if (base.Columns.ContainsKey(9)) { return base.Columns[9]; } else { return null; } } set { if (base.Columns.ContainsKey(9)) { base.Columns[9] = value; } else { base.Columns.Add(9, value); } } }
		/// <summary>PID: 310 | Type: read</summary>
		public System.Object Senderstransportparamssecondarysourceport { get { if (base.Columns.ContainsKey(9)) { return base.Columns[9]; } else { return null; } } set { if (base.Columns.ContainsKey(9)) { base.Columns[9] = value; } else { base.Columns.Add(9, value); } } }
		/// <summary>PID: 311 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Senderstransportparamssecondarydestinationport_311 { get { if (base.Columns.ContainsKey(10)) { return base.Columns[10]; } else { return null; } } set { if (base.Columns.ContainsKey(10)) { base.Columns[10] = value; } else { base.Columns.Add(10, value); } } }
		/// <summary>PID: 311 | Type: read</summary>
		public System.Object Senderstransportparamssecondarydestinationport { get { if (base.Columns.ContainsKey(10)) { return base.Columns[10]; } else { return null; } } set { if (base.Columns.ContainsKey(10)) { base.Columns[10] = value; } else { base.Columns.Add(10, value); } } }
		/// <summary>PID: 312 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Senderstransportparamssecondarydestinationip_312 { get { if (base.Columns.ContainsKey(11)) { return base.Columns[11]; } else { return null; } } set { if (base.Columns.ContainsKey(11)) { base.Columns[11] = value; } else { base.Columns.Add(11, value); } } }
		/// <summary>PID: 312 | Type: read</summary>
		public System.Object Senderstransportparamssecondarydestinationip { get { if (base.Columns.ContainsKey(11)) { return base.Columns[11]; } else { return null; } } set { if (base.Columns.ContainsKey(11)) { base.Columns[11] = value; } else { base.Columns.Add(11, value); } } }
		/// <summary>PID: 313 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Senderstransportparamssecondaryrtpenabled_313 { get { if (base.Columns.ContainsKey(12)) { return base.Columns[12]; } else { return null; } } set { if (base.Columns.ContainsKey(12)) { base.Columns[12] = value; } else { base.Columns.Add(12, value); } } }
		/// <summary>PID: 313 | Type: read</summary>
		public System.Object Senderstransportparamssecondaryrtpenabled { get { if (base.Columns.ContainsKey(12)) { return base.Columns[12]; } else { return null; } } set { if (base.Columns.ContainsKey(12)) { base.Columns[12] = value; } else { base.Columns.Add(12, value); } } }
		/// <summary>PID: 314 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Sendersdescription_314 { get { if (base.Columns.ContainsKey(13)) { return base.Columns[13]; } else { return null; } } set { if (base.Columns.ContainsKey(13)) { base.Columns[13] = value; } else { base.Columns.Add(13, value); } } }
		/// <summary>PID: 314 | Type: read</summary>
		public System.Object Sendersdescription { get { if (base.Columns.ContainsKey(13)) { return base.Columns[13]; } else { return null; } } set { if (base.Columns.ContainsKey(13)) { base.Columns[13] = value; } else { base.Columns.Add(13, value); } } }
		/// <summary>PID: 315 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Senderssdpfile_string_315 { get { if (base.Columns.ContainsKey(14)) { return base.Columns[14]; } else { return null; } } set { if (base.Columns.ContainsKey(14)) { base.Columns[14] = value; } else { base.Columns.Add(14, value); } } }
		/// <summary>PID: 315 | Type: read</summary>
		public System.Object Senderssdpfile_string { get { if (base.Columns.ContainsKey(14)) { return base.Columns[14]; } else { return null; } } set { if (base.Columns.ContainsKey(14)) { base.Columns[14] = value; } else { base.Columns.Add(14, value); } } }
		/// <summary>PID: 316 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Senderssdpfile_url_316 { get { if (base.Columns.ContainsKey(15)) { return base.Columns[15]; } else { return null; } } set { if (base.Columns.ContainsKey(15)) { base.Columns[15] = value; } else { base.Columns.Add(15, value); } } }
		/// <summary>PID: 316 | Type: read</summary>
		public System.Object Senderssdpfile_url { get { if (base.Columns.ContainsKey(15)) { return base.Columns[15]; } else { return null; } } set { if (base.Columns.ContainsKey(15)) { base.Columns[15] = value; } else { base.Columns.Add(15, value); } } }
		/// <summary>PID: 317 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Sendersactivationtime_317 { get { if (base.Columns.ContainsKey(16)) { return base.Columns[16]; } else { return null; } } set { if (base.Columns.ContainsKey(16)) { base.Columns[16] = value; } else { base.Columns.Add(16, value); } } }
		/// <summary>PID: 317 | Type: read</summary>
		public System.Object Sendersactivationtime { get { if (base.Columns.ContainsKey(16)) { return base.Columns[16]; } else { return null; } } set { if (base.Columns.ContainsKey(16)) { base.Columns[16] = value; } else { base.Columns.Add(16, value); } } }
		/// <summary>PID: 318 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Sendersprimaryinterfacebinding_318 { get { if (base.Columns.ContainsKey(17)) { return base.Columns[17]; } else { return null; } } set { if (base.Columns.ContainsKey(17)) { base.Columns[17] = value; } else { base.Columns.Add(17, value); } } }
		/// <summary>PID: 318 | Type: read</summary>
		public System.Object Sendersprimaryinterfacebinding { get { if (base.Columns.ContainsKey(17)) { return base.Columns[17]; } else { return null; } } set { if (base.Columns.ContainsKey(17)) { base.Columns[17] = value; } else { base.Columns.Add(17, value); } } }
		/// <summary>PID: 319 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public System.Object Senderssecondaryinterfacebinding_319 { get { if (base.Columns.ContainsKey(18)) { return base.Columns[18]; } else { return null; } } set { if (base.Columns.ContainsKey(18)) { base.Columns[18] = value; } else { base.Columns.Add(18, value); } } }
		/// <summary>PID: 319 | Type: read</summary>
		public System.Object Senderssecondaryinterfacebinding { get { if (base.Columns.ContainsKey(18)) { return base.Columns[18]; } else { return null; } } set { if (base.Columns.ContainsKey(18)) { base.Columns[18] = value; } else { base.Columns.Add(18, value); } } }
		public SendersQActionRow() : base(0, 19) { }
		public SendersQActionRow(System.Object[] oRow) : base(0, 19, oRow) { }
		public static implicit operator SendersQActionRow(System.Object[] source) { return new SendersQActionRow(source); }
		public static implicit operator System.Object[](SendersQActionRow source) { return source.ToObjectArray(); }
	}
}