name: DataMiner CICD Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: []
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+-**"
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-**"
  pull_request:
    branches: []
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  #https://github.com/NuGet/Home/issues/7575#issuecomment-443801131
  NUGET_RESTORE_MSBUILD_ARGS: /p:Configuration=Release

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  CI:
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/Automation Master Workflow.yml@ForceOldCatalogApi
    with:
      referenceName: ${{ github.ref_name }}
      runNumber: ${{ github.run_number }}
      referenceType: ${{ github.ref_type }}
      repository: ${{ github.repository }}
      owner: ${{ github.repository_owner }}
      sonarCloudProjectName: SkylineCommunications_SLC-AS-SatOps
    secrets:
      # The API-key: generated in the DCP Admin app (https://admin.dataminer.services/) as authentication for a certain DataMiner System.
      api-key: ${{ secrets.DATAMINER_DEPLOY_KEY }}
      sonarCloudToken: ${{ secrets.SONARCLOUD }}
    
  # # Optional 0 or More CD Jobs as needed
  # CD:
  #   if: github.ref_type == 'tag'
  #   environment: production
  #   name: CD
  #   runs-on: ubuntu-latest
  #   needs: CI

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Skyline DataMiner Deploy Action
  #       uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1
  #       with:
  #         # Stage deploy
  #         stage: Deploy
  #         # The API-key: generated in the DCP Admin app (https://admin.dataminer.services/) as authentication for a certain DataMiner System.
  #         api-key: ${{ secrets.DATAMINER_DEPLOY_KEY }}
  #         # Id of the uploaded artifact
  #         artifact-id: ${{ needs.CI.outputs.artifact-id }}
